### ISSUE TITLE
Port hw files to final project repo.

### ISSUE THREAD

**Issue by TylerFermUCI** [UC-Irvine-CS175/final-project-gan-guardians#2]
#### Description
Port over the files/data classes from homework into this repo.

#### Files
- `data_utils.py`
- `bps_dataset.py`
- `augmentation.py`

#### Tasks
- [ ] Import `data_utils.py`
- [ ] Test `data_utils.py` works on everybody's machine.
- [ ] Import `bps_dataset.py`
- [ ] Test `bps_dataset.py` works on everybody's machine.
- [ ] Import `augmentation.py`
- [ ] Test `augmentation.py` works on everybody's machine.
