### ISSUE TITLE
Image Classification

### ISSUE THREAD

**Issue by TylerFermUCI** [UC-Irvine-CS175/final-project-gan-guardians#8]
## Description
Create an image classifier that can detect if the BPS image has been radiated with Fe or X-ray. Using this classifier, we can test to see if the images created by the GAN are valid. We will first get an accuracy score (from the image classifier) using validation data/images (images without any GAN images). We will then get an accuracy score using a combination of validation data and GAN images. Finally, we will get one more accuracy score using just GAN images. The image classifier will be some off the shelf model.

## Files
- Whatever (new) files are needed.

## Tasks
- [ ] Make an image classifier.
- [ ] Test it on the validation data/images to ensure it works.
- [ ] Tune hyperparameters if needed (if the accuracy score is really low).

**Comment by tariqsb** [comment]
So far we have made changes to `resnet101.py` to accommodate supervised transfer learning, but we most likely need to edit our file architecture to make sure everything is in the right place.
